//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACT_FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACT_FACTURA()
        {
            this.FACT_FACTURA_DETALLE = new HashSet<FACT_FACTURA_DETALLE>();
        }
    
        public int Id { get; set; }
        public int ProductoId { get; set; }
        public int ClienteId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Total { get; set; }
        public int Estregistro { get; set; }
    
        public virtual FACT_CLIENTE FACT_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACT_FACTURA_DETALLE> FACT_FACTURA_DETALLE { get; set; }
    }
}
