//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACT_FACTURA_DETALLE
    {
        public int Id { get; set; }
        public int FacturaId { get; set; }
        public int ProductoId { get; set; }
        public int Cant { get; set; }
        public int Subtotal { get; set; }
        public int Estregistro { get; set; }
    
        public virtual FACT_FACTURA FACT_FACTURA { get; set; }
        public virtual FACT_PRODUCTO FACT_PRODUCTO { get; set; }
    }
}
