//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaBL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelEntities : DbContext
    {
        public ModelEntities()
            : base("name=ModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOM_TEST> DOM_TEST { get; set; }
        public virtual DbSet<FACT_CLIENTE> FACT_CLIENTE { get; set; }
        public virtual DbSet<FACT_PRODUCTO> FACT_PRODUCTO { get; set; }
        public virtual DbSet<FACT_FACTURA> FACT_FACTURA { get; set; }
        public virtual DbSet<FACT_FACTURA_DETALLE> FACT_FACTURA_DETALLE { get; set; }
    }
}
